apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-player-deployement
  labels:
    app: music-player
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nmusic-player
  template:
    metadata:
      labels:
        app: nmusic-player
    spec:
      containers:
      - name: music-player
        image: manikanta101/music-playlist:latest
        ports:
        - containerPort: 3000
