apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-player-deployement
  labels:
    app: music-player
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Music-Player
  template:
    metadata:
      labels:
        app: music-player
    spec:
      containers:
      - name: music-player
        image: manikanta101/music-playlist:1
        ports:
        - containerPort: 3000
