apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-player-deployement
  labels:
    app: music-player
spec:
  replicas: 3
  selector:
    matchLabels:
      app: music-player
  template:
    metadata:
      labels:
        app: music-player
    spec:
      containers:
      - name: music-player
        image: manikanta101/music-playlist:3
        ports:
        - containerPort: 3000
app_configuration:
  s3.release.config:
    s3_endpoint: India
    s3_pollingurltimeout: '120'
    s3_tempsubfolder: my-store/
  database.release.config: 
      musicplayer_db_assetdbname: M106712
      musicplayer_db_dbcontext_name: MSCDbContext.M106712
      musiscplaye_db_dbname: M106712
      musicplayer_db_dbserver: APMU2498678
      musicplayer_db_dbuser: MUSICG
      musicplayer_db_dbuser_db_replication_dbname: M106712_rpt
      musicplayer_db_dbuser_db_replication_dbuser: MUSICG
