apiVersion: apps/v1
kind: Deployment
metadata:
  name: Music-player-deployment
  labels:
    app: Music-Player
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Music-Player
  template:
    metadata:
      labels:
        app: Music-Player
    spec:
      containers:
      - name: Music-player-deployment
        image: nmanikanta101/music-playlist:3
        ports:
        - containerPort: 3000
