apiVersion: v1
kind: Service
metadata:
  name: music-player-service
spec:
  type: LoadBalancer
  selector:
    app: music-player
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000
app_configuration:
  s3.release.config:
      s3_bucketname: harekrisna
      '
  database.release.config: 
      musicplayer_db_assetdbname: M106712
      musicplayer_db_dbcontext_name: MSCDbContext.M106712
      musiscplaye_db_dbname: M106712
      musicplayer_db_dbserver: APMU2498678
      musicplayer_db_dbuser: MUSICG
      musicplayer_db_dbuser_db_replication_dbname: M106712_rpt
      musicplayer_db_dbuser_db_replication_dbuser: MUSICG
  
