apiVersion: v1
kind: Service
metadata:
  name: music-player-service
spec:
  type: LoadBalancer
  selector:
    app: music-player
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000
app_configuration:
  s3.release.config:
      s3_bucketname: MUSICPLAYER
  database.release.config: 
      musicplayer_db_assetdbname: MUSIC1234
      musicplayer_db_dbcontext_name: MSCDbContext.M12345
      musiscplaye_db_dbname: M123456
      musicplayer_db_dbserver: MUSICDBSERVER
      musicplayer_db_dbuser: MUSICDBUSER
      musicplayer_db_dbuser_db_replication_dbname: MUSICDBREPLICA
      musicplayer_db_dbuser_db_replication_dbuser: MUSIDCDBREPLICAUSER
  
